name = "XtalsPyTools"
uuid = "eeb819d4-c189-4e83-a288-887db76b1875"
authors = ["SimonEnsemble <cory.simon@oregonstate.edu>"]
version = "0.0.1"

[deps]
FIGlet = "3064a664-84fe-4d92-92c7-ed492f3d8fae"
Xtals = "ede5f01d-793e-4c47-9885-c447d1f18d6d"

[compat]
Xtals = "0.3"
FIGlet = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
